const moduleContent = [
    {
        "id": 1,
        "section": "Time Tundra",
        "header": "Interest rates, and terms",
        "body": "this is interest rate and this is a term",
        "exercise_type": "MCQ",
    },
    {
        "id": 2,
        "section": "Time Tundra",
        "header": "Managed funds (including retirement funds)",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 3,
        "section": "Time Tundra",
        "header": "Bonds (govt bonds, company bonds, bond maturity dates)",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 4,
        "section": "Time Tundra",
        "header": "Review",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "",
    },
    {
        "id": 5,
        "section": "Commodity Cave",
        "header": "Commodity basics - why buy, storing value in items rather than money",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 6,
        "section": "Commodity Cave",
        "header": "How to get into commodities - owning it, index funds, commodity funds",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 7,
        "section": "Commodity Cave",
        "header": "Futures and futures based commodity funds -  what is a future?",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 8,
        "section": "Commodity Cave",
        "header": "Review",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "",
    },
    {
        "id": 9,
        "section": "Property Plains",
        "header": "Property basics, mortgages, capital gains",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 10,
        "section": "Property Plains",
        "header": "Equity and leverage - using houses to buy more houses",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 11,
        "section": "Property Plains",
        "header": "Renting, tenants, property management, yield",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 12,
        "section": "Property Plains",
        "header": "Review",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "",
    },
    {
        "id": 13,
        "section": "Forex Forest",
        "header": "How do you make money on forex, what influences forex",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 14,
        "section": "Forex Forest",
        "header": "Forex fundamentals, chart reading, bid-ask, pips",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 15,
        "section": "Forex Forest",
        "header": "Leverage and magnifying money, risks",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 16,
        "section": "Forex Forest",
        "header": "Review",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "",
    },
    {
        "id": 17,
        "section": "Crypto Cove",
        "header": "What is crypto? What is the blockchain? How does this make me money?",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 18,
        "section": "Crypto Cove",
        "header": "Crypto extended - wallets, addresses/hashes, gas fees, contracts",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 19,
        "section": "Crypto Cove",
        "header": "Coins and derivatives, trading and virtual monkeys",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 20,
        "section": "Crypto Cove",
        "header": "Review",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "",
    },
    {
        "id": 21,
        "section": "Stock Slopes",
        "header": "Stock basics - public companies, what is a share, how does this help companies and people",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 22,
        "section": "Stock Slopes",
        "header": "Mutual funds, index funds, etfs, what they are, diversification",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 23,
        "section": "Stock Slopes",
        "header": "Options and futures (how does this differ from commodity futures)",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 24,
        "section": "Stock Slopes",
        "header": "Review",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 25,
        "section": "THE GRAND FINALE",
        "header": "finale stuff",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 26,
        "section": "THE GRAND FINALE",
        "header": "Interest rates, and terms",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 27,
        "section": "THE GRAND FINALE",
        "header": "Interest rates, and terms",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
    {
        "id": 28,
        "section": "THE GRAND FINALE",
        "header": "Interest rates, and terms",
        "body": "lfkskj sdfijoisd jfosudhf siufh sidufh sdhfsdfh",
        "exercise_type": "MCQ",
    },
];

export default moduleContent;